services:
  service:
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=service_db
      - DB_NAME=service
      - DB_USER=postgres
      - DB_PASS=1337
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - service_db

  service_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1337
