# Generated by Django 4.2.3 on 2023-07-27 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techquestions',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='techquestions',
            name='grade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='service.grade', verbose_name='Грейд'),
        ),
        migrations.AlterField(
            model_name='techquestions',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='service.job', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='techquestions',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
    ]
